[2024-04-01T05:33:59.531+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:33:59.054443+00:00 [queued]>
[2024-04-01T05:33:59.538+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:33:59.054443+00:00 [queued]>
[2024-04-01T05:33:59.539+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-04-01T05:33:59.550+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_1_runConsumer> on 2024-04-01 05:33:59.054443+00:00
[2024-04-01T05:33:59.555+0000] {standard_task_runner.py:57} INFO - Started process 1506 to run task
[2024-04-01T05:33:59.558+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_1_runConsumer', 'manual__2024-04-01T05:33:59.054443+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmp9g0fajji']
[2024-04-01T05:33:59.559+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask task_1_runConsumer
[2024-04-01T05:33:59.597+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:33:59.054443+00:00 [running]> on host 977df1ccf323
[2024-04-01T05:33:59.661+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_1_runConsumer' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T05:33:59.054443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T05:33:59.054443+00:00'
[2024-04-01T05:33:59.662+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T05:33:59.663+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/producer.py']
[2024-04-01T05:33:59.674+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T05:34:01.133+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-01T05:34:01.133+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/producer.py", line 11, in <module>
[2024-04-01T05:34:01.133+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(bootstrap_servers=bootstrap_servers2)
[2024-04-01T05:34:01.133+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
[2024-04-01T05:34:01.134+0000] {subprocess.py:93} INFO -     client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
[2024-04-01T05:34:01.134+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
[2024-04-01T05:34:01.134+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version(timeout=check_timeout)
[2024-04-01T05:34:01.134+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/client_async.py", line 900, in check_version
[2024-04-01T05:34:01.134+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2024-04-01T05:34:01.134+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-04-01T05:34:01.142+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-01T05:34:01.150+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-01T05:34:01.153+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=deploy_project_kafkaClickhouse, task_id=task_1_runConsumer, execution_date=20240401T053359, start_date=20240401T053359, end_date=20240401T053401
[2024-04-01T05:34:01.163+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task task_1_runConsumer (Bash command failed. The command returned a non-zero exit code 1.; 1506)
[2024-04-01T05:34:01.177+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-01T05:34:01.194+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
