[2024-04-01T05:34:07.137+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:33:59.054443+00:00 [queued]>
[2024-04-01T05:34:07.143+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:33:59.054443+00:00 [queued]>
[2024-04-01T05:34:07.143+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-04-01T05:34:07.152+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_1_runConsumer> on 2024-04-01 05:33:59.054443+00:00
[2024-04-01T05:34:07.156+0000] {standard_task_runner.py:57} INFO - Started process 1510 to run task
[2024-04-01T05:34:07.159+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_1_runConsumer', 'manual__2024-04-01T05:33:59.054443+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmplthedln_']
[2024-04-01T05:34:07.159+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask task_1_runConsumer
[2024-04-01T05:34:07.193+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:33:59.054443+00:00 [running]> on host 977df1ccf323
[2024-04-01T05:34:07.244+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_1_runConsumer' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T05:33:59.054443+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T05:33:59.054443+00:00'
[2024-04-01T05:34:07.245+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T05:34:07.245+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/producer.py']
[2024-04-01T05:34:07.255+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T05:34:09.475+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-01T05:34:09.475+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/producer.py", line 11, in <module>
[2024-04-01T05:34:09.475+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(bootstrap_servers=bootstrap_servers2)
[2024-04-01T05:34:09.475+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
[2024-04-01T05:34:09.476+0000] {subprocess.py:93} INFO -     client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
[2024-04-01T05:34:09.476+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
[2024-04-01T05:34:09.476+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version(timeout=check_timeout)
[2024-04-01T05:34:09.476+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/client_async.py", line 927, in check_version
[2024-04-01T05:34:09.476+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2024-04-01T05:34:09.476+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-04-01T05:34:09.483+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-01T05:34:09.492+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-01T05:34:09.494+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=deploy_project_kafkaClickhouse, task_id=task_1_runConsumer, execution_date=20240401T053359, start_date=20240401T053407, end_date=20240401T053409
[2024-04-01T05:34:09.503+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task task_1_runConsumer (Bash command failed. The command returned a non-zero exit code 1.; 1510)
[2024-04-01T05:34:09.536+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-01T05:34:09.552+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
