[2024-04-01T05:46:36.292+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_2_runProducer manual__2024-04-01T05:46:33.590007+00:00 [queued]>
[2024-04-01T05:46:36.299+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_2_runProducer manual__2024-04-01T05:46:33.590007+00:00 [queued]>
[2024-04-01T05:46:36.299+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-04-01T05:46:36.308+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_2_runProducer> on 2024-04-01 05:46:33.590007+00:00
[2024-04-01T05:46:36.312+0000] {standard_task_runner.py:57} INFO - Started process 1745 to run task
[2024-04-01T05:46:36.315+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_2_runProducer', 'manual__2024-04-01T05:46:33.590007+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmplq9d7o8c']
[2024-04-01T05:46:36.316+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask task_2_runProducer
[2024-04-01T05:46:36.351+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_2_runProducer manual__2024-04-01T05:46:33.590007+00:00 [running]> on host 977df1ccf323
[2024-04-01T05:46:36.404+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_2_runProducer' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T05:46:33.590007+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T05:46:33.590007+00:00'
[2024-04-01T05:46:36.404+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T05:46:36.405+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/consumer.py']
[2024-04-01T05:46:36.415+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T05:46:36.836+0000] {subprocess.py:93} INFO - %3|1711950396.836|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
[2024-04-01T05:46:36.933+0000] {subprocess.py:93} INFO - %3|1711950396.933|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
[2024-04-01T05:47:07.068+0000] {subprocess.py:93} INFO - %3|1711950427.068|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 5 identical error(s) suppressed)
[2024-04-01T05:47:45.322+0000] {subprocess.py:93} INFO - %3|1711950465.322|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:48:25.320+0000] {subprocess.py:93} INFO - %3|1711950505.320|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:49:02.676+0000] {subprocess.py:93} INFO - %3|1711950542.676|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:49:42.101+0000] {subprocess.py:93} INFO - %3|1711950582.101|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:50:21.073+0000] {subprocess.py:93} INFO - %3|1711950621.072|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:51:01.071+0000] {subprocess.py:93} INFO - %3|1711950661.071|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:51:37.288+0000] {subprocess.py:93} INFO - %3|1711950697.288|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:52:14.907+0000] {subprocess.py:93} INFO - %3|1711950734.907|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:52:53.407+0000] {subprocess.py:93} INFO - %3|1711950773.407|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:53:31.891+0000] {subprocess.py:93} INFO - %3|1711950811.891|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:54:07.521+0000] {subprocess.py:93} INFO - %3|1711950847.521|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:54:45.287+0000] {subprocess.py:93} INFO - %3|1711950885.287|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:55:24.105+0000] {subprocess.py:93} INFO - %3|1711950924.105|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:56:01.809+0000] {subprocess.py:93} INFO - %3|1711950961.809|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:56:38.472+0000] {subprocess.py:93} INFO - %3|1711950998.472|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:57:17.088+0000] {subprocess.py:93} INFO - %3|1711951037.088|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:57:57.086+0000] {subprocess.py:93} INFO - %3|1711951077.086|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:58:32.797+0000] {subprocess.py:93} INFO - %3|1711951112.797|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:59:11.143+0000] {subprocess.py:93} INFO - %3|1711951151.143|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:59:51.142+0000] {subprocess.py:93} INFO - %3|1711951191.141|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:00:31.139+0000] {subprocess.py:93} INFO - %3|1711951231.139|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:01:08.728+0000] {subprocess.py:93} INFO - %3|1711951268.728|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:01:46.954+0000] {subprocess.py:93} INFO - %3|1711951306.954|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:02:16.955+0000] {subprocess.py:93} INFO - %3|1711951336.955|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 3 identical error(s) suppressed)
[2024-04-01T06:02:56.955+0000] {subprocess.py:93} INFO - %3|1711951376.955|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:03:33.873+0000] {subprocess.py:93} INFO - %3|1711951413.873|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:04:12.157+0000] {subprocess.py:93} INFO - %3|1711951452.157|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:04:52.156+0000] {subprocess.py:93} INFO - %3|1711951492.156|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:05:32.153+0000] {subprocess.py:93} INFO - %3|1711951532.152|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:06:11.704+0000] {subprocess.py:93} INFO - %3|1711951571.703|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:06:49.590+0000] {subprocess.py:93} INFO - %3|1711951609.590|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:07:27.753+0000] {subprocess.py:93} INFO - %3|1711951647.753|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:08:05.538+0000] {subprocess.py:93} INFO - %3|1711951685.538|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:08:45.536+0000] {subprocess.py:93} INFO - %3|1711951725.536|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:09:23.234+0000] {subprocess.py:93} INFO - %3|1711951763.234|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:10:00.397+0000] {subprocess.py:93} INFO - %3|1711951800.397|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:10:38.629+0000] {subprocess.py:93} INFO - %3|1711951838.629|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:11:17.636+0000] {subprocess.py:93} INFO - %3|1711951877.636|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:11:56.881+0000] {subprocess.py:93} INFO - %3|1711951916.881|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:12:35.956+0000] {subprocess.py:93} INFO - %3|1711951955.956|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:13:15.956+0000] {subprocess.py:93} INFO - %3|1711951995.956|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:13:55.955+0000] {subprocess.py:93} INFO - %3|1711952035.955|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:14:33.284+0000] {subprocess.py:93} INFO - %3|1711952073.284|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:15:11.942+0000] {subprocess.py:93} INFO - %3|1711952111.942|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:15:51.940+0000] {subprocess.py:93} INFO - %3|1711952151.940|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:16:29.199+0000] {subprocess.py:93} INFO - %3|1711952189.199|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:17:08.482+0000] {subprocess.py:93} INFO - %3|1711952228.482|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:17:46.968+0000] {subprocess.py:93} INFO - %3|1711952266.968|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:18:25.853+0000] {subprocess.py:93} INFO - %3|1711952305.853|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:19:02.453+0000] {subprocess.py:93} INFO - %3|1711952342.453|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:19:40.629+0000] {subprocess.py:93} INFO - %3|1711952380.629|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:20:16.458+0000] {subprocess.py:93} INFO - %3|1711952416.458|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:20:54.500+0000] {subprocess.py:93} INFO - %3|1711952454.500|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:21:34.498+0000] {subprocess.py:93} INFO - %3|1711952494.498|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:22:12.608+0000] {subprocess.py:93} INFO - %3|1711952532.608|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:22:49.243+0000] {subprocess.py:93} INFO - %3|1711952569.243|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:23:26.169+0000] {subprocess.py:93} INFO - %3|1711952606.169|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:24:06.169+0000] {subprocess.py:93} INFO - %3|1711952646.169|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:24:42.156+0000] {subprocess.py:93} INFO - %3|1711952682.156|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:25:12.157+0000] {subprocess.py:93} INFO - %3|1711952712.157|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 3 identical error(s) suppressed)
[2024-04-01T06:25:49.990+0000] {subprocess.py:93} INFO - %3|1711952749.990|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:26:27.416+0000] {subprocess.py:93} INFO - %3|1711952787.416|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:27:03.737+0000] {subprocess.py:93} INFO - %3|1711952823.737|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:27:43.736+0000] {subprocess.py:93} INFO - %3|1711952863.736|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:28:13.737+0000] {subprocess.py:93} INFO - %3|1711952893.737|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 3 identical error(s) suppressed)
[2024-04-01T06:28:52.242+0000] {subprocess.py:93} INFO - %3|1711952932.242|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:29:31.425+0000] {subprocess.py:93} INFO - %3|1711952971.424|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:30:10.052+0000] {subprocess.py:93} INFO - %3|1711953010.052|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:30:50.051+0000] {subprocess.py:93} INFO - %3|1711953050.051|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:31:28.578+0000] {subprocess.py:93} INFO - %3|1711953088.578|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:32:04.636+0000] {subprocess.py:93} INFO - %3|1711953124.636|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:32:43.180+0000] {subprocess.py:93} INFO - %3|1711953163.180|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:33:21.999+0000] {subprocess.py:93} INFO - %3|1711953201.999|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:34:01.011+0000] {subprocess.py:93} INFO - %3|1711953241.011|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:34:39.349+0000] {subprocess.py:93} INFO - %3|1711953279.349|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:35:18.946+0000] {subprocess.py:93} INFO - %3|1711953318.946|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:35:57.466+0000] {subprocess.py:93} INFO - %3|1711953357.466|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:36:36.805+0000] {subprocess.py:93} INFO - %3|1711953396.805|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:37:14.759+0000] {subprocess.py:93} INFO - %3|1711953434.759|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:37:52.290+0000] {subprocess.py:93} INFO - %3|1711953472.290|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:38:30.353+0000] {subprocess.py:93} INFO - %3|1711953510.352|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:39:08.917+0000] {subprocess.py:93} INFO - %3|1711953548.917|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:39:47.636+0000] {subprocess.py:93} INFO - %3|1711953587.636|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:40:27.635+0000] {subprocess.py:93} INFO - %3|1711953627.635|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:41:05.150+0000] {subprocess.py:93} INFO - %3|1711953665.150|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:41:45.148+0000] {subprocess.py:93} INFO - %3|1711953705.148|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:42:25.148+0000] {subprocess.py:93} INFO - %3|1711953745.148|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:43:02.386+0000] {subprocess.py:93} INFO - %3|1711953782.386|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:43:39.976+0000] {subprocess.py:93} INFO - %3|1711953819.976|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:44:17.716+0000] {subprocess.py:93} INFO - %3|1711953857.716|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:44:57.714+0000] {subprocess.py:93} INFO - %3|1711953897.714|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:45:33.258+0000] {subprocess.py:93} INFO - %3|1711953933.258|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:46:12.623+0000] {subprocess.py:93} INFO - %3|1711953972.623|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:46:51.925+0000] {subprocess.py:93} INFO - %3|1711954011.925|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:47:29.815+0000] {subprocess.py:93} INFO - %3|1711954049.815|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:48:09.813+0000] {subprocess.py:93} INFO - %3|1711954089.813|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:48:49.568+0000] {subprocess.py:93} INFO - %3|1711954129.568|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:49:27.090+0000] {subprocess.py:93} INFO - %3|1711954167.089|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:50:05.967+0000] {subprocess.py:93} INFO - %3|1711954205.967|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:50:45.965+0000] {subprocess.py:93} INFO - %3|1711954245.964|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:51:25.017+0000] {subprocess.py:93} INFO - %3|1711954285.017|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:52:02.919+0000] {subprocess.py:93} INFO - %3|1711954322.919|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:52:42.917+0000] {subprocess.py:93} INFO - %3|1711954362.917|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:52:48.500+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2024-04-01T06:52:48.502+0000] {process_utils.py:131} INFO - Sending 15 to group 1745. PIDs of all processes in the group: [1746, 1745]
[2024-04-01T06:52:48.502+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1745
[2024-04-01T06:52:48.503+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-01T06:52:48.503+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-04-01T06:52:48.529+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1746, status='terminated', started='05:46:36') (1746) terminated with exit code None
[2024-04-01T06:52:48.530+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1745, status='terminated', exitcode=0, started='05:46:35') (1745) terminated with exit code 0
