[2024-04-01T07:25:19.870+0000] {processor.py:157} INFO - Started process (PID=7192) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:25:19.871+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:25:19.871+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:25:19.871+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:25:19.880+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:25:19.878+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:25:19.880+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:25:19.895+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.028 seconds
[2024-04-01T07:26:32.575+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:26:32.577+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:26:32.578+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:26:32.578+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:26:32.585+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:26:32.583+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:26:32.585+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:26:32.601+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.028 seconds
[2024-04-01T07:27:03.139+0000] {processor.py:157} INFO - Started process (PID=49) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:27:03.140+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:27:03.142+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:27:03.142+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:27:03.148+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:27:03.147+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:27:03.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:27:03.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.027 seconds
[2024-04-01T07:27:33.412+0000] {processor.py:157} INFO - Started process (PID=67) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:27:33.413+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:27:33.415+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:27:33.415+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:27:33.421+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:27:33.420+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:27:33.421+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:27:33.435+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.025 seconds
[2024-04-01T07:28:03.683+0000] {processor.py:157} INFO - Started process (PID=85) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:28:03.684+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:28:03.685+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:28:03.685+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:28:03.692+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:28:03.691+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:28:03.693+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:28:03.707+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.027 seconds
[2024-04-01T07:28:33.914+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:28:33.915+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:28:33.917+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:28:33.917+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:28:33.924+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:28:33.922+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:28:33.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:28:33.941+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.031 seconds
[2024-04-01T07:29:04.192+0000] {processor.py:157} INFO - Started process (PID=121) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:29:04.193+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:29:04.195+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:29:04.194+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:29:04.201+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:29:04.200+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:29:04.202+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:29:04.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.026 seconds
[2024-04-01T07:29:34.461+0000] {processor.py:157} INFO - Started process (PID=139) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:29:34.461+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:29:34.463+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:29:34.462+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:29:34.469+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:29:34.468+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:29:34.470+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:29:34.485+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.028 seconds
[2024-04-01T07:30:04.740+0000] {processor.py:157} INFO - Started process (PID=157) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:30:04.741+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:30:04.742+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:30:04.742+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:30:04.749+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:30:04.747+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:30:04.749+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:30:04.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.026 seconds
[2024-04-01T07:30:35.010+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:30:35.010+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:30:35.012+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:30:35.012+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:30:35.018+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:30:35.017+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:30:35.019+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:30:35.033+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.026 seconds
[2024-04-01T07:31:05.278+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:31:05.279+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:31:05.280+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:31:05.280+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:31:05.287+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:31:05.285+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:31:05.287+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:31:05.303+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.028 seconds
[2024-04-01T07:31:35.550+0000] {processor.py:157} INFO - Started process (PID=211) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:31:35.550+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:31:35.552+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:31:35.552+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:31:35.559+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:31:35.557+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:31:35.559+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:31:35.573+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.026 seconds
[2024-04-01T07:32:05.814+0000] {processor.py:157} INFO - Started process (PID=229) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:32:05.815+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:32:05.817+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:32:05.817+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:32:05.824+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:32:05.822+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:32:05.824+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:32:05.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.027 seconds
[2024-04-01T07:32:36.103+0000] {processor.py:157} INFO - Started process (PID=248) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:32:36.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:32:36.106+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:32:36.106+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:32:36.112+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:32:36.111+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:32:36.113+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:32:36.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.028 seconds
[2024-04-01T07:33:06.337+0000] {processor.py:157} INFO - Started process (PID=266) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:33:06.338+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:33:06.339+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:33:06.339+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:33:06.346+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:33:06.344+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:33:06.346+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:33:06.362+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.029 seconds
[2024-04-01T07:33:10.482+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:33:10.482+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:33:10.484+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:33:10.484+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:33:10.490+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:33:10.489+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:33:10.491+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:33:10.505+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.026 seconds
[2024-04-01T07:33:40.705+0000] {processor.py:157} INFO - Started process (PID=295) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:33:40.706+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:33:40.707+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:33:40.707+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:33:40.714+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:33:40.712+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:33:40.715+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:33:40.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.027 seconds
[2024-04-01T07:34:11.076+0000] {processor.py:157} INFO - Started process (PID=315) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:34:11.077+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:34:11.078+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:34:11.078+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:34:11.084+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:34:11.083+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:34:11.084+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:34:11.098+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.024 seconds
[2024-04-01T07:34:41.297+0000] {processor.py:157} INFO - Started process (PID=333) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:34:41.298+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:34:41.299+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:34:41.299+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:34:41.305+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:34:41.304+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:34:41.306+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:34:41.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.024 seconds
[2024-04-01T07:35:11.521+0000] {processor.py:157} INFO - Started process (PID=350) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:35:11.522+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:35:11.523+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:35:11.523+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:35:11.529+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:35:11.528+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:35:11.530+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:35:11.544+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.025 seconds
[2024-04-01T07:35:41.791+0000] {processor.py:157} INFO - Started process (PID=368) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:35:41.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:35:41.794+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:35:41.793+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:35:41.800+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:35:41.798+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:35:41.801+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:35:41.816+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.027 seconds
[2024-04-01T07:36:12.057+0000] {processor.py:157} INFO - Started process (PID=387) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:36:12.057+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:36:12.059+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:12.058+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:36:12.064+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:12.063+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/exe.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/exe.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:36:12.065+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:36:12.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.024 seconds
[2024-04-01T07:36:39.268+0000] {processor.py:157} INFO - Started process (PID=405) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:36:39.269+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:36:39.269+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:39.269+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:36:39.278+0000] {processor.py:839} INFO - DAG(s) dict_keys(['deploy_project_kafkaClickhouse2']) retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:36:39.359+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:39.359+0000] {manager.py:499} INFO - Created Permission View: %s
[2024-04-01T07:36:39.367+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:39.367+0000] {manager.py:499} INFO - Created Permission View: %s
[2024-04-01T07:36:39.374+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:39.373+0000] {manager.py:499} INFO - Created Permission View: %s
[2024-04-01T07:36:39.374+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:39.374+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:deploy_project_kafkaClickhouse2' as access control is unset.
[2024-04-01T07:36:39.374+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:39.374+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2024-04-01T07:36:39.383+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:39.382+0000] {dag.py:2937} INFO - Creating ORM DAG for deploy_project_kafkaClickhouse2
[2024-04-01T07:36:39.393+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:39.392+0000] {dag.py:3696} INFO - Setting next_dagrun for deploy_project_kafkaClickhouse2 to 2024-03-30T09:30:00+00:00, run_after=2024-03-31T09:30:00+00:00
[2024-04-01T07:36:39.406+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.141 seconds
[2024-04-01T07:36:44.302+0000] {processor.py:157} INFO - Started process (PID=406) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:36:44.303+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:36:44.303+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:44.303+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:36:44.313+0000] {processor.py:839} INFO - DAG(s) dict_keys(['deploy_project_kafkaClickhouse']) retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:36:44.401+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:44.401+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:deploy_project_kafkaClickhouse' as access control is unset.
[2024-04-01T07:36:44.401+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:44.401+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2024-04-01T07:36:44.409+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:44.409+0000] {dag.py:2937} INFO - Creating ORM DAG for deploy_project_kafkaClickhouse
[2024-04-01T07:36:44.419+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:44.419+0000] {dag.py:3696} INFO - Setting next_dagrun for deploy_project_kafkaClickhouse to 2024-03-30T09:30:00+00:00, run_after=2024-03-31T09:30:00+00:00
[2024-04-01T07:36:44.433+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.134 seconds
[2024-04-01T07:37:14.571+0000] {processor.py:157} INFO - Started process (PID=424) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:37:14.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:37:14.573+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:37:14.572+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:37:14.582+0000] {processor.py:839} INFO - DAG(s) dict_keys(['deploy_project_kafkaClickhouse']) retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:37:14.603+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:37:14.603+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2024-04-01T07:37:14.621+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:37:14.621+0000] {dag.py:3696} INFO - Setting next_dagrun for deploy_project_kafkaClickhouse to 2024-03-30T09:30:00+00:00, run_after=2024-03-31T09:30:00+00:00
[2024-04-01T07:37:14.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.067 seconds
[2024-04-01T07:37:44.821+0000] {processor.py:157} INFO - Started process (PID=442) to work on /opt/airflow/dags/exe.py
[2024-04-01T07:37:44.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/exe.py for tasks to queue
[2024-04-01T07:37:44.822+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:37:44.822+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/exe.py
[2024-04-01T07:37:44.832+0000] {processor.py:839} INFO - DAG(s) dict_keys(['deploy_project_kafkaClickhouse']) retrieved from /opt/airflow/dags/exe.py
[2024-04-01T07:37:44.853+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:37:44.853+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2024-04-01T07:37:44.871+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:37:44.871+0000] {dag.py:3696} INFO - Setting next_dagrun for deploy_project_kafkaClickhouse to 2024-03-30T09:30:00+00:00, run_after=2024-03-31T09:30:00+00:00
[2024-04-01T07:37:44.883+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exe.py took 0.065 seconds
