[2024-04-01T07:35:37.654+0000] {processor.py:157} INFO - Started process (PID=358) to work on /opt/airflow/dags/execute2.py
[2024-04-01T07:35:37.655+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/execute2.py for tasks to queue
[2024-04-01T07:35:37.657+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:35:37.657+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/execute2.py
[2024-04-01T07:35:37.663+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:35:37.662+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/execute2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/execute2.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:35:37.663+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/execute2.py
[2024-04-01T07:35:37.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/execute2.py took 0.028 seconds
[2024-04-01T07:36:07.922+0000] {processor.py:157} INFO - Started process (PID=377) to work on /opt/airflow/dags/execute2.py
[2024-04-01T07:36:07.923+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/execute2.py for tasks to queue
[2024-04-01T07:36:07.925+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:07.925+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/execute2.py
[2024-04-01T07:36:07.931+0000] {logging_mixin.py:151} INFO - [2024-04-01T07:36:07.929+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/execute2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/execute2.py", line 30, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 930, in __init__
    self.dag = dag
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1045, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1106, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 2540, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-04-01T07:36:07.931+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/execute2.py
[2024-04-01T07:36:07.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/execute2.py took 0.028 seconds
