[2024-04-01T05:28:48.189+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:28:47.358605+00:00 [queued]>
[2024-04-01T05:28:48.197+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:28:47.358605+00:00 [queued]>
[2024-04-01T05:28:48.197+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-04-01T05:28:48.207+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_1_runConsumer> on 2024-04-01 05:28:47.358605+00:00
[2024-04-01T05:28:48.212+0000] {standard_task_runner.py:57} INFO - Started process 1388 to run task
[2024-04-01T05:28:48.214+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_1_runConsumer', 'manual__2024-04-01T05:28:47.358605+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmpaxfwc699']
[2024-04-01T05:28:48.215+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask task_1_runConsumer
[2024-04-01T05:28:48.286+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:28:47.358605+00:00 [running]> on host 977df1ccf323
[2024-04-01T05:28:48.350+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_1_runConsumer' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T05:28:47.358605+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T05:28:47.358605+00:00'
[2024-04-01T05:28:48.351+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T05:28:48.351+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/consumer.py']
[2024-04-01T05:28:48.362+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T05:28:49.148+0000] {subprocess.py:93} INFO - %3|1711949329.148|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
[2024-04-01T05:28:49.337+0000] {subprocess.py:93} INFO - %3|1711949329.337|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
[2024-04-01T05:29:23.940+0000] {subprocess.py:93} INFO - %3|1711949363.940|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 5 identical error(s) suppressed)
[2024-04-01T05:30:01.536+0000] {subprocess.py:93} INFO - %3|1711949401.536|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:30:40.424+0000] {subprocess.py:93} INFO - %3|1711949440.424|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:31:18.947+0000] {subprocess.py:93} INFO - %3|1711949478.947|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:31:57.934+0000] {subprocess.py:93} INFO - %3|1711949517.934|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:32:37.934+0000] {subprocess.py:93} INFO - %3|1711949557.934|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:33:16.533+0000] {subprocess.py:93} INFO - %3|1711949596.533|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:33:55.461+0000] {subprocess.py:93} INFO - %3|1711949635.461|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:34:33.215+0000] {subprocess.py:93} INFO - %3|1711949673.215|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:35:11.078+0000] {subprocess.py:93} INFO - %3|1711949711.078|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:35:47.084+0000] {subprocess.py:93} INFO - %3|1711949747.084|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:36:24.383+0000] {subprocess.py:93} INFO - %3|1711949784.383|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:37:03.404+0000] {subprocess.py:93} INFO - %3|1711949823.404|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:37:43.104+0000] {subprocess.py:93} INFO - %3|1711949863.104|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:38:20.622+0000] {subprocess.py:93} INFO - %3|1711949900.622|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:38:59.471+0000] {subprocess.py:93} INFO - %3|1711949939.471|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:39:39.470+0000] {subprocess.py:93} INFO - %3|1711949979.470|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:40:19.468+0000] {subprocess.py:93} INFO - %3|1711950019.468|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:40:59.258+0000] {subprocess.py:93} INFO - %3|1711950059.258|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:41:33.595+0000] {subprocess.py:93} INFO - %3|1711950093.595|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:42:12.798+0000] {subprocess.py:93} INFO - %3|1711950132.798|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:42:52.797+0000] {subprocess.py:93} INFO - %3|1711950172.796|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:43:31.002+0000] {subprocess.py:93} INFO - %3|1711950211.002|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:44:11.001+0000] {subprocess.py:93} INFO - %3|1711950251.001|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:44:50.182+0000] {subprocess.py:93} INFO - %3|1711950290.182|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:45:29.982+0000] {subprocess.py:93} INFO - %3|1711950329.982|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:46:08.349+0000] {subprocess.py:93} INFO - %3|1711950368.349|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:46:46.572+0000] {subprocess.py:93} INFO - %3|1711950406.572|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:47:25.832+0000] {subprocess.py:93} INFO - %3|1711950445.832|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:48:05.559+0000] {subprocess.py:93} INFO - %3|1711950485.559|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:48:41.430+0000] {subprocess.py:93} INFO - %3|1711950521.430|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:49:19.740+0000] {subprocess.py:93} INFO - %3|1711950559.740|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:49:49.741+0000] {subprocess.py:93} INFO - %3|1711950589.741|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 3 identical error(s) suppressed)
[2024-04-01T05:50:27.463+0000] {subprocess.py:93} INFO - %3|1711950627.463|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:51:07.461+0000] {subprocess.py:93} INFO - %3|1711950667.460|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:51:45.022+0000] {subprocess.py:93} INFO - %3|1711950705.022|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:52:22.662+0000] {subprocess.py:93} INFO - %3|1711950742.662|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:53:02.119+0000] {subprocess.py:93} INFO - %3|1711950782.118|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:53:36.481+0000] {subprocess.py:93} INFO - %3|1711950816.481|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:54:16.116+0000] {subprocess.py:93} INFO - %3|1711950856.115|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:54:51.989+0000] {subprocess.py:93} INFO - %3|1711950891.988|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:55:31.479+0000] {subprocess.py:93} INFO - %3|1711950931.478|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:56:11.476+0000] {subprocess.py:93} INFO - %3|1711950971.476|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:56:49.545+0000] {subprocess.py:93} INFO - %3|1711951009.545|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:57:25.318+0000] {subprocess.py:93} INFO - %3|1711951045.318|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:58:03.769+0000] {subprocess.py:93} INFO - %3|1711951083.769|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:58:33.769+0000] {subprocess.py:93} INFO - %3|1711951113.769|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 3 identical error(s) suppressed)
[2024-04-01T05:59:10.018+0000] {subprocess.py:93} INFO - %3|1711951150.018|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T05:59:49.076+0000] {subprocess.py:93} INFO - %3|1711951189.076|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:00:29.075+0000] {subprocess.py:93} INFO - %3|1711951229.075|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:01:06.529+0000] {subprocess.py:93} INFO - %3|1711951266.529|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:01:40.813+0000] {subprocess.py:93} INFO - %3|1711951300.813|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:02:19.323+0000] {subprocess.py:93} INFO - %3|1711951339.323|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:02:59.321+0000] {subprocess.py:93} INFO - %3|1711951379.321|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:03:34.614+0000] {subprocess.py:93} INFO - %3|1711951414.613|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:04:11.892+0000] {subprocess.py:93} INFO - %3|1711951451.892|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:04:48.682+0000] {subprocess.py:93} INFO - %3|1711951488.682|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:05:25.295+0000] {subprocess.py:93} INFO - %3|1711951525.295|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:06:01.087+0000] {subprocess.py:93} INFO - %3|1711951561.087|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:06:40.912+0000] {subprocess.py:93} INFO - %3|1711951600.912|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:07:20.353+0000] {subprocess.py:93} INFO - %3|1711951640.353|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:07:58.579+0000] {subprocess.py:93} INFO - %3|1711951678.579|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:08:38.022+0000] {subprocess.py:93} INFO - %3|1711951718.022|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:09:18.022+0000] {subprocess.py:93} INFO - %3|1711951758.022|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:09:54.578+0000] {subprocess.py:93} INFO - %3|1711951794.578|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:10:33.544+0000] {subprocess.py:93} INFO - %3|1711951833.544|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:11:07.270+0000] {subprocess.py:93} INFO - %3|1711951867.270|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:11:44.357+0000] {subprocess.py:93} INFO - %3|1711951904.357|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:12:24.335+0000] {subprocess.py:93} INFO - %3|1711951944.334|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:13:03.000+0000] {subprocess.py:93} INFO - %3|1711951983.000|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:13:42.888+0000] {subprocess.py:93} INFO - %3|1711952022.888|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:14:16.461+0000] {subprocess.py:93} INFO - %3|1711952056.461|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:14:56.460+0000] {subprocess.py:93} INFO - %3|1711952096.460|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:15:34.943+0000] {subprocess.py:93} INFO - %3|1711952134.943|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:16:13.264+0000] {subprocess.py:93} INFO - %3|1711952173.264|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:16:51.531+0000] {subprocess.py:93} INFO - %3|1711952211.531|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:17:31.529+0000] {subprocess.py:93} INFO - %3|1711952251.529|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:18:05.555+0000] {subprocess.py:93} INFO - %3|1711952285.555|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:18:43.919+0000] {subprocess.py:93} INFO - %3|1711952323.919|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:19:21.401+0000] {subprocess.py:93} INFO - %3|1711952361.401|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:19:51.405+0000] {subprocess.py:93} INFO - %3|1711952391.405|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 3 identical error(s) suppressed)
[2024-04-01T06:20:27.931+0000] {subprocess.py:93} INFO - %3|1711952427.931|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:21:07.931+0000] {subprocess.py:93} INFO - %3|1711952467.931|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:21:47.929+0000] {subprocess.py:93} INFO - %3|1711952507.929|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:22:21.514+0000] {subprocess.py:93} INFO - %3|1711952541.513|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:22:58.404+0000] {subprocess.py:93} INFO - %3|1711952578.404|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:23:35.867+0000] {subprocess.py:93} INFO - %3|1711952615.867|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:24:15.866+0000] {subprocess.py:93} INFO - %3|1711952655.866|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:24:54.785+0000] {subprocess.py:93} INFO - %3|1711952694.785|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:25:34.173+0000] {subprocess.py:93} INFO - %3|1711952734.173|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:26:12.890+0000] {subprocess.py:93} INFO - %3|1711952772.890|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:26:52.868+0000] {subprocess.py:93} INFO - %3|1711952812.868|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:27:32.868+0000] {subprocess.py:93} INFO - %3|1711952852.868|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:28:12.867+0000] {subprocess.py:93} INFO - %3|1711952892.866|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:28:50.751+0000] {subprocess.py:93} INFO - %3|1711952930.751|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:29:30.751+0000] {subprocess.py:93} INFO - %3|1711952970.751|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:30:07.482+0000] {subprocess.py:93} INFO - %3|1711953007.482|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:30:46.392+0000] {subprocess.py:93} INFO - %3|1711953046.392|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:31:24.224+0000] {subprocess.py:93} INFO - %3|1711953084.224|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:32:03.224+0000] {subprocess.py:93} INFO - %3|1711953123.224|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:32:41.521+0000] {subprocess.py:93} INFO - %3|1711953161.521|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:33:19.162+0000] {subprocess.py:93} INFO - %3|1711953199.162|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:33:57.882+0000] {subprocess.py:93} INFO - %3|1711953237.882|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:34:34.490+0000] {subprocess.py:93} INFO - %3|1711953274.490|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:35:14.474+0000] {subprocess.py:93} INFO - %3|1711953314.474|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:35:50.406+0000] {subprocess.py:93} INFO - %3|1711953350.406|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:36:29.309+0000] {subprocess.py:93} INFO - %3|1711953389.309|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:37:05.950+0000] {subprocess.py:93} INFO - %3|1711953425.949|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:37:45.948+0000] {subprocess.py:93} INFO - %3|1711953465.948|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:38:22.588+0000] {subprocess.py:93} INFO - %3|1711953502.588|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:38:58.681+0000] {subprocess.py:93} INFO - %3|1711953538.681|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:39:36.883+0000] {subprocess.py:93} INFO - %3|1711953576.883|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:40:15.170+0000] {subprocess.py:93} INFO - %3|1711953615.170|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:40:45.171+0000] {subprocess.py:93} INFO - %3|1711953645.171|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 3 identical error(s) suppressed)
[2024-04-01T06:41:24.511+0000] {subprocess.py:93} INFO - %3|1711953684.511|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:42:04.362+0000] {subprocess.py:93} INFO - %3|1711953724.362|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:42:43.754+0000] {subprocess.py:93} INFO - %3|1711953763.754|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:43:21.945+0000] {subprocess.py:93} INFO - %3|1711953801.945|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:44:01.944+0000] {subprocess.py:93} INFO - %3|1711953841.943|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:44:41.943+0000] {subprocess.py:93} INFO - %3|1711953881.942|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:45:19.458+0000] {subprocess.py:93} INFO - %3|1711953919.457|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:45:57.160+0000] {subprocess.py:93} INFO - %3|1711953957.159|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:46:37.158+0000] {subprocess.py:93} INFO - %3|1711953997.158|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:47:12.879+0000] {subprocess.py:93} INFO - %3|1711954032.879|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:47:42.880+0000] {subprocess.py:93} INFO - %3|1711954062.880|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 3 identical error(s) suppressed)
[2024-04-01T06:48:21.296+0000] {subprocess.py:93} INFO - %3|1711954101.296|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:49:00.836+0000] {subprocess.py:93} INFO - %3|1711954140.836|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:49:40.835+0000] {subprocess.py:93} INFO - %3|1711954180.835|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:50:19.087+0000] {subprocess.py:93} INFO - %3|1711954219.087|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:50:59.086+0000] {subprocess.py:93} INFO - %3|1711954259.086|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:51:37.138+0000] {subprocess.py:93} INFO - %3|1711954297.138|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:52:16.476+0000] {subprocess.py:93} INFO - %3|1711954336.476|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:52:56.475+0000] {subprocess.py:93} INFO - %3|1711954376.475|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:53:35.079+0000] {subprocess.py:93} INFO - %3|1711954415.079|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:54:13.140+0000] {subprocess.py:93} INFO - %3|1711954453.139|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:54:53.139+0000] {subprocess.py:93} INFO - %3|1711954493.138|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:55:33.040+0000] {subprocess.py:93} INFO - %3|1711954533.039|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:56:09.277+0000] {subprocess.py:93} INFO - %3|1711954569.277|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:56:46.909+0000] {subprocess.py:93} INFO - %3|1711954606.909|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:57:24.260+0000] {subprocess.py:93} INFO - %3|1711954644.260|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:58:01.652+0000] {subprocess.py:93} INFO - %3|1711954681.652|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:58:39.822+0000] {subprocess.py:93} INFO - %3|1711954719.822|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:59:19.820+0000] {subprocess.py:93} INFO - %3|1711954759.820|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T06:59:55.744+0000] {subprocess.py:93} INFO - %3|1711954795.744|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:00:33.299+0000] {subprocess.py:93} INFO - %3|1711954833.299|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:01:13.299+0000] {subprocess.py:93} INFO - %3|1711954873.299|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:01:51.285+0000] {subprocess.py:93} INFO - %3|1711954911.285|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:02:28.942+0000] {subprocess.py:93} INFO - %3|1711954948.942|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:03:07.563+0000] {subprocess.py:93} INFO - %3|1711954987.563|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:03:45.933+0000] {subprocess.py:93} INFO - %3|1711955025.932|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:04:25.933+0000] {subprocess.py:93} INFO - %3|1711955065.932|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:05:03.279+0000] {subprocess.py:93} INFO - %3|1711955103.279|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:05:43.136+0000] {subprocess.py:93} INFO - %3|1711955143.136|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:06:21.256+0000] {subprocess.py:93} INFO - %3|1711955181.256|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:07:00.484+0000] {subprocess.py:93} INFO - %3|1711955220.484|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:07:35.415+0000] {subprocess.py:93} INFO - %3|1711955255.415|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 127.0.0.1:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
[2024-04-01T07:07:51.094+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-04-01T07:07:51.096+0000] {process_utils.py:131} INFO - Sending 15 to group 1388. PIDs of all processes in the group: [1389, 1388]
[2024-04-01T07:07:51.097+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1388
[2024-04-01T07:07:51.097+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-01T07:07:51.097+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-04-01T07:07:51.105+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-04-01T07:07:51.108+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=deploy_project_kafkaClickhouse, task_id=task_1_runConsumer, execution_date=20240401T052847, start_date=20240401T052848, end_date=20240401T070751
[2024-04-01T07:07:51.119+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task task_1_runConsumer ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(deploy_project_kafkaClickhouse, task_1_runConsumer, manual__2024-04-01T05:28:47.358605+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'task_1_runConsumer', 'dag_id': 'deploy_project_kafkaClickhouse', 'run_id': 'manual__2024-04-01T05:28:47.358605+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 4, 1, 5, 28, 48, 190139, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 4, 1, 7, 7, 51, 108436, tzinfo=Timezone('UTC')), 'duration': 5942}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1388)
[2024-04-01T07:07:51.149+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1388, status='terminated', exitcode=1, started='05:28:47') (1388) terminated with exit code 1
[2024-04-01T07:07:51.149+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1389, status='terminated', started='05:28:48') (1389) terminated with exit code None
