[2024-04-01T09:30:07.231+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer scheduled__2024-03-31T09:30:00+00:00 [queued]>
[2024-04-01T09:30:07.237+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer scheduled__2024-03-31T09:30:00+00:00 [queued]>
[2024-04-01T09:30:07.237+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-04-01T09:30:07.246+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_Clickhouse_Consumer> on 2024-03-31 09:30:00+00:00
[2024-04-01T09:30:07.250+0000] {standard_task_runner.py:57} INFO - Started process 2148 to run task
[2024-04-01T09:30:07.252+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_Clickhouse_Consumer', 'scheduled__2024-03-31T09:30:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmpo_217mrd']
[2024-04-01T09:30:07.253+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask task_Clickhouse_Consumer
[2024-04-01T09:30:07.288+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer scheduled__2024-03-31T09:30:00+00:00 [running]> on host 977df1ccf323
[2024-04-01T09:30:07.339+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_Clickhouse_Consumer' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T09:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-31T09:30:00+00:00'
[2024-04-01T09:30:07.340+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T09:30:07.340+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/consumer.py']
[2024-04-01T09:30:07.350+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T09:30:07.733+0000] {subprocess.py:93} INFO - Error on socket shutdown: [Errno 107] Transport endpoint is not connected
[2024-04-01T09:30:07.734+0000] {subprocess.py:93} INFO - Consumer started
[2024-04-01T09:30:07.734+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-01T09:30:07.735+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/columns/service.py", line 139, in get_column_by_spec
[2024-04-01T09:30:07.735+0000] {subprocess.py:93} INFO -     cls = column_by_type[spec]
[2024-04-01T09:30:07.735+0000] {subprocess.py:93} INFO - KeyError: ')org.apache.hadoop.ipc.RPC$Version'
[2024-04-01T09:30:07.735+0000] {subprocess.py:93} INFO - 
[2024-04-01T09:30:07.735+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2024-04-01T09:30:07.735+0000] {subprocess.py:93} INFO - 
[2024-04-01T09:30:07.735+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-01T09:30:07.735+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/consumer.py", line 99, in <module>
[2024-04-01T09:30:07.735+0000] {subprocess.py:93} INFO -     main()
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/consumer.py", line 46, in main
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -     clickhouse_client.execute(CREATE_TABLE_QUERY)
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 382, in execute
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -     rv = self.process_ordinary_query(
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -     return self.receive_result(with_column_types=with_column_types,
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 213, in receive_result
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -     return result.get_result()
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -     for packet in self.packet_generator:
[2024-04-01T09:30:07.736+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 229, in packet_generator
[2024-04-01T09:30:07.737+0000] {subprocess.py:93} INFO -     packet = self.receive_packet()
[2024-04-01T09:30:07.737+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 243, in receive_packet
[2024-04-01T09:30:07.737+0000] {subprocess.py:93} INFO -     packet = self.connection.receive_packet()
[2024-04-01T09:30:07.737+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 592, in receive_packet
[2024-04-01T09:30:07.737+0000] {subprocess.py:93} INFO -     packet.block = self.receive_data()
[2024-04-01T09:30:07.737+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 652, in receive_data
[2024-04-01T09:30:07.737+0000] {subprocess.py:93} INFO -     return reader.read(use_numpy=use_numpy)
[2024-04-01T09:30:07.737+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/streams/native.py", line 83, in read
[2024-04-01T09:30:07.737+0000] {subprocess.py:93} INFO -     column = read_column(
[2024-04-01T09:30:07.737+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/columns/service.py", line 152, in read_column
[2024-04-01T09:30:07.738+0000] {subprocess.py:93} INFO -     col = get_column_by_spec(column_spec, column_options, use_numpy=use_numpy)
[2024-04-01T09:30:07.738+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/columns/service.py", line 143, in get_column_by_spec
[2024-04-01T09:30:07.738+0000] {subprocess.py:93} INFO -     raise errors.UnknownTypeError('Unknown type {}'.format(spec))
[2024-04-01T09:30:07.738+0000] {subprocess.py:93} INFO - clickhouse_driver.errors.UnknownTypeError: Code: 50. Unknown type )org.apache.hadoop.ipc.RPC$Version
[2024-04-01T09:30:07.753+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-01T09:30:07.763+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-01T09:30:07.765+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=deploy_project_kafkaClickhouse, task_id=task_Clickhouse_Consumer, execution_date=20240331T093000, start_date=20240401T093007, end_date=20240401T093007
[2024-04-01T09:30:07.775+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 57 for task task_Clickhouse_Consumer (Bash command failed. The command returned a non-zero exit code 1.; 2148)
[2024-04-01T09:30:07.785+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-01T09:30:07.798+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
