[2024-04-01T08:32:47.259+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer manual__2024-04-01T08:00:35.897187+00:00 [queued]>
[2024-04-01T08:32:47.275+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer manual__2024-04-01T08:00:35.897187+00:00 [queued]>
[2024-04-01T08:32:47.275+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-04-01T08:32:47.288+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_Clickhouse_Consumer> on 2024-04-01 08:00:35.897187+00:00
[2024-04-01T08:32:47.293+0000] {standard_task_runner.py:57} INFO - Started process 1074 to run task
[2024-04-01T08:32:47.296+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_Clickhouse_Consumer', 'manual__2024-04-01T08:00:35.897187+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmp6lwhao3v']
[2024-04-01T08:32:47.297+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask task_Clickhouse_Consumer
[2024-04-01T08:32:47.340+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer manual__2024-04-01T08:00:35.897187+00:00 [running]> on host 977df1ccf323
[2024-04-01T08:32:47.419+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_Clickhouse_Consumer' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T08:00:35.897187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T08:00:35.897187+00:00'
[2024-04-01T08:32:47.422+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T08:32:47.423+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/consumer.py']
[2024-04-01T08:32:47.441+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T08:35:25.830+0000] {subprocess.py:93} INFO - Subscribed to Kafka topic: log_data
[2024-04-01T08:35:25.830+0000] {subprocess.py:93} INFO - 
[2024-04-01T08:35:25.830+0000] {subprocess.py:93} INFO - inserting data into ClickHouse...
[2024-04-01T08:35:25.831+0000] {subprocess.py:93} INFO - 
[2024-04-01T08:35:25.831+0000] {subprocess.py:93} INFO - done
[2024-04-01T08:35:25.831+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-01T08:35:25.831+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/consumer.py", line 97, in <module>
[2024-04-01T08:35:25.831+0000] {subprocess.py:93} INFO -     print('done')
[2024-04-01T08:35:25.831+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/consumer.py", line 86, in main
[2024-04-01T08:35:25.831+0000] {subprocess.py:93} INFO - 
[2024-04-01T08:35:25.831+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 382, in execute
[2024-04-01T08:35:25.832+0000] {subprocess.py:93} INFO -     rv = self.process_ordinary_query(
[2024-04-01T08:35:25.832+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
[2024-04-01T08:35:25.832+0000] {subprocess.py:93} INFO -     return self.receive_result(with_column_types=with_column_types,
[2024-04-01T08:35:25.832+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 213, in receive_result
[2024-04-01T08:35:25.832+0000] {subprocess.py:93} INFO -     return result.get_result()
[2024-04-01T08:35:25.832+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
[2024-04-01T08:35:25.832+0000] {subprocess.py:93} INFO -     for packet in self.packet_generator:
[2024-04-01T08:35:25.832+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 229, in packet_generator
[2024-04-01T08:35:25.832+0000] {subprocess.py:93} INFO -     packet = self.receive_packet()
[2024-04-01T08:35:25.832+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 246, in receive_packet
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO -     raise packet.exception
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO - clickhouse_driver.errors.ServerException: Code: 60.
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO - DB::Exception: Table default.logs doesn't exist. Stack trace:
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO - 
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO - 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO - 1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0xa89b823 in /usr/bin/clickhouse
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO - 2. void std::__1::__optional_storage_base<DB::Exception, false>::__construct<int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x1352ac0f in /usr/bin/clickhouse
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO - 3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const @ 0x13519082 in /usr/bin/clickhouse
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO - 4. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const @ 0x1352126b in /usr/bin/clickhouse
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO - 5. DB::InterpreterInsertQuery::getTable(DB::ASTInsertQuery&) @ 0x13a49ab0 in /usr/bin/clickhouse
[2024-04-01T08:35:25.833+0000] {subprocess.py:93} INFO - 6. DB::InterpreterInsertQuery::execute() @ 0x13a4b7a9 in /usr/bin/clickhouse
[2024-04-01T08:35:25.834+0000] {subprocess.py:93} INFO - 7. ? @ 0x13d1434c in /usr/bin/clickhouse
[2024-04-01T08:35:25.834+0000] {subprocess.py:93} INFO - 8. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
[2024-04-01T08:35:25.834+0000] {subprocess.py:93} INFO - 9. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
[2024-04-01T08:35:25.834+0000] {subprocess.py:93} INFO - 10. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
[2024-04-01T08:35:25.834+0000] {subprocess.py:93} INFO - 11. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
[2024-04-01T08:35:25.834+0000] {subprocess.py:93} INFO - 12. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
[2024-04-01T08:35:25.834+0000] {subprocess.py:93} INFO - 13. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
[2024-04-01T08:35:25.834+0000] {subprocess.py:93} INFO - 14. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
[2024-04-01T08:35:25.834+0000] {subprocess.py:93} INFO - 15. ? @ 0x7f5a9c959609 in ?
[2024-04-01T08:35:25.834+0000] {subprocess.py:93} INFO - 16. __clone @ 0x7f5a9c880293 in ?
[2024-04-01T08:35:25.835+0000] {subprocess.py:93} INFO - 
[2024-04-01T08:35:25.851+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-01T08:35:25.863+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-01T08:35:25.867+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=deploy_project_kafkaClickhouse, task_id=task_Clickhouse_Consumer, execution_date=20240401T080035, start_date=20240401T083247, end_date=20240401T083525
[2024-04-01T08:35:25.883+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task task_Clickhouse_Consumer (Bash command failed. The command returned a non-zero exit code 1.; 1074)
[2024-04-01T08:35:25.900+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-01T08:35:25.912+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
