[2024-04-01T07:18:47.097+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T07:18:45.841862+00:00 [queued]>
[2024-04-01T07:18:47.104+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T07:18:45.841862+00:00 [queued]>
[2024-04-01T07:18:47.104+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-04-01T07:18:47.113+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_1_runConsumer> on 2024-04-01 07:18:45.841862+00:00
[2024-04-01T07:18:47.118+0000] {standard_task_runner.py:57} INFO - Started process 3312 to run task
[2024-04-01T07:18:47.121+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_1_runConsumer', 'manual__2024-04-01T07:18:45.841862+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmp8we3lmt2']
[2024-04-01T07:18:47.122+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask task_1_runConsumer
[2024-04-01T07:18:47.159+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T07:18:45.841862+00:00 [running]> on host 977df1ccf323
[2024-04-01T07:18:47.217+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_1_runConsumer' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T07:18:45.841862+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T07:18:45.841862+00:00'
[2024-04-01T07:18:47.218+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T07:18:47.219+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/consumer.py']
[2024-04-01T07:18:47.229+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T07:21:38.521+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-04-01T07:21:38.524+0000] {process_utils.py:131} INFO - Sending 15 to group 3312. PIDs of all processes in the group: [3314, 3312]
[2024-04-01T07:21:38.524+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 3312
[2024-04-01T07:21:38.524+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-01T07:21:38.525+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-04-01T07:21:38.548+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-04-01T07:21:38.551+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=deploy_project_kafkaClickhouse, task_id=task_1_runConsumer, execution_date=20240401T071845, start_date=20240401T071847, end_date=20240401T072138
[2024-04-01T07:21:38.562+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task task_1_runConsumer ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(deploy_project_kafkaClickhouse, task_1_runConsumer, manual__2024-04-01T07:18:45.841862+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'task_1_runConsumer', 'dag_id': 'deploy_project_kafkaClickhouse', 'run_id': 'manual__2024-04-01T07:18:45.841862+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 4, 1, 7, 18, 47, 97532, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 4, 1, 7, 21, 38, 551305, tzinfo=Timezone('UTC')), 'duration': 171}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 3312)
[2024-04-01T07:21:38.576+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3312, status='terminated', exitcode=1, started='07:18:46') (3312) terminated with exit code 1
[2024-04-01T07:21:38.577+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3314, status='terminated', started='07:18:46') (3314) terminated with exit code None
